-- =============================================================================
-- Desafio PliQ — Mini CX · Schema (PostgreSQL)
-- =============================================================================
-- Espelha data/seed.json: 3 pesquisas, contatos (alunos) e respostas.
-- Regra crítica do domínio: soft delete (deleted_at). Todo registro com
-- deleted_at NOT NULL está logicamente excluído e NÃO pode entrar em nenhuma
-- leitura/agregação/exportação (WHERE deleted_at IS NULL em toda query).
--
-- Este arquivo roda automaticamente via docker-entrypoint-initdb.d na primeira
-- subida do container (ver docker-compose). Os dados vêm em 02-seed.sql.
-- =============================================================================

-- Busca de contatos por nome/e-mail usa LIKE '%termo%' (contém). Trigramas
-- permitem índice GIN que acelera esse padrão — btree comum só ajudaria prefixo.
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- -----------------------------------------------------------------------------
-- surveys — as 3 pesquisas. No seed não têm deleted_at (não são excluíveis).
-- type restringe a escala: NPS (0–10) x CSAT (1–5). Nunca misturar as métricas.
-- -----------------------------------------------------------------------------
CREATE TABLE surveys (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT        NOT NULL,
    type       TEXT        NOT NULL CHECK (type IN ('NPS', 'CSAT')),
    created_at TIMESTAMPTZ NOT NULL
);

-- -----------------------------------------------------------------------------
-- contacts — os alunos. Criados/editados/excluídos pela API.
-- deleted_at = soft delete: DELETE marca a data, não apaga a linha.
-- -----------------------------------------------------------------------------
CREATE TABLE contacts (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT        NOT NULL,
    email      TEXT        NOT NULL,
    segment    TEXT,                            -- opcional: Plano Black/Fit/Corporativo
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ
);

-- E-mail único, case-insensitive, APENAS entre contatos ativos: o índice parcial
-- (WHERE deleted_at IS NULL) implementa a regra de negócio nativamente — o mesmo
-- e-mail volta a ficar livre depois que o contato que o usava é excluído.
-- Como bônus, serve de índice para lookup exato por e-mail.
CREATE UNIQUE INDEX ux_contacts_email_active
    ON contacts (lower(email))
    WHERE deleted_at IS NULL;

-- Busca "contém" por nome e e-mail (CRUD lista com busca). GIN + trigramas.
-- Parcial: só buscamos contatos ativos, então o índice não carrega os excluídos.
CREATE INDEX idx_contacts_name_trgm
    ON contacts USING gin (lower(name) gin_trgm_ops)
    WHERE deleted_at IS NULL;
CREATE INDEX idx_contacts_email_trgm
    ON contacts USING gin (lower(email) gin_trgm_ops)
    WHERE deleted_at IS NULL;

-- -----------------------------------------------------------------------------
-- responses — as respostas das pesquisas.
-- score cobre as duas escalas (0–10); a classificação NPS (detrator/neutro/
-- promotor) e a média CSAT são feitas em SQL na consulta de resumo.
-- deleted_at = soft delete (respostas removidas a pedido do titular / LGPD).
-- -----------------------------------------------------------------------------
CREATE TABLE responses (
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    survey_id    INT         NOT NULL REFERENCES surveys (id),
    contact_id   INT         NOT NULL REFERENCES contacts (id),
    score        SMALLINT    NOT NULL CHECK (score BETWEEN 0 AND 10),
    comment      TEXT,
    channel      TEXT        NOT NULL CHECK (channel IN ('whatsapp', 'email', 'link')),
    responded_at TIMESTAMPTZ NOT NULL,
    deleted_at   TIMESTAMPTZ
);

-- Índices parciais (WHERE deleted_at IS NULL) porque TODA leitura já filtra
-- excluídos — o índice fica menor e cobre exatamente o recorte consultado.
--   responded_at: filtro de período (from/to) e agrupamento mensal do resumo.
CREATE INDEX idx_responses_responded_at
    ON responses (responded_at)
    WHERE deleted_at IS NULL;
--   contact_id: histórico de respostas de um contato.
CREATE INDEX idx_responses_contact_id
    ON responses (contact_id)
    WHERE deleted_at IS NULL;
--   survey_id: JOIN com surveys e filtro por surveyId no resumo.
CREATE INDEX idx_responses_survey_id
    ON responses (survey_id)
    WHERE deleted_at IS NULL;
